import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutProviders from "@/LayoutTemplate/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next-Json Fake Api Creater",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutProviders children={children} />
      </body>
    </html>
  );
}
